### ISSUE TITLE
memory corruption issues

### ISSUE THREAD

**Issue by BrainSlayer** [cifsd-team/ksmbd#289]
while testing which debuggin enabled i discovered that smbd has likelly memory corruption issues. i wasnt able yet to get it working with authentication since the connection simply was hanging without any logging output. but with no authentication i was turning the arm based system into a hanging state and logs like this here are showing that there is a serious issue somewhere
[  570.401968] ksmbd: find_next:6151: filename string = test.bin ñêEc4¤dd█Õõ²~\1ËeC4(ÙT(µÁqÑï và:´º▒<¸Ë)X(rÅ÷┐,*^ù§í$‗BpÔÚ±Ì╝;´z¹╗e:zê_Õñ%░r       í³┌kü+╣£╔Þ╝åR!ÓF+gUCÄå6╣4Á
[  570.401968] )┘²Î[Û}¬¿¹zg╝¥╩¦Ç{OUò╦báı¥ÿÿßwÌ°.CÑ­├>æË?Ë!FmG<¬oÍ█┴LÈ
[  570.401972] ksmbd: smb_populate_readdir_entry:5697: info_level : 514, buf_len :10620, next_offset : 248, data_count :

this was just reading data from a samba share

**Comment by BrainSlayer** [comment]
in addition. the issue seem to happen in my testcase if i have one share already connection unauthenticated. this works. if i now connect a second one from a different computer which is authenticated the authentication will hang and i get such corrupted messages from the  unauthenticated session. if i just do a single authenticated connection it works. so something is very strange here

**Comment by namjaejeon** [comment]
> while testing which debuggin enabled i discovered that smbd has likelly memory corruption issues. i wasnt able yet to get it working with authentication since the connection simply was hanging without any logging output. but with no authentication i was turning the arm based system into a hanging state and logs like this here are showing that there is a serious issue somewhere

This issue is related with your another report(" length can run bellow zero which may cause stack corruption in follow up code ") ? I am wondering it is fixed after changing len with len > 0.

**Comment by hclee** [comment]
I think that this issue happens because the string does not have a null character. So we must print this string with the length of it.

**Comment by hclee** [comment]
#291 is merged. 
@BrainSlayer , Could you test it again?

**Comment by BrainSlayer** [comment]
@namjaejeon it might be related. i was seeking in that function what could cause such corrupted message which can only be caused by a broken stack. so i found this code problem, but it doesnt mean that the issue will be caused by that function. depending on the length of the argument and the content of the string. it may run bellow zero and will cause a buffer overrun. i already fixed that in my tree and so far i havent seen this issue again. but its no proof. i may add some debug code to find out if this case can ever happen

**Comment by namjaejeon** [comment]
@hclee Thanks for your patch:)

@BrainSlayer Okay.
Pushed two patches to master branch. (https://github.com/cifsd-team/smbd/commit/ff9beb2a13a47286bab45d784978c6a7ca0ad017, https://github.com/cifsd-team/smbd/commit/5a07c4128dcb7a4ee7dadd1c2afef6f004e7d85c)

Thanks for your feedback!

**Comment by namjaejeon** [comment]
@BrainSlayer Could you please tell me which kind of client is used ? windows XP ? or linux kernel cifs client ?

**Comment by namjaejeon** [comment]
@BrainSlayer I pushed related patches to master branch. Could you confirm this issue is clear ?

**Comment by BrainSlayer** [comment]
@namjaejeon i have not seen this issue again. so its likelly fixed.

**Comment by BrainSlayer** [comment]
@namjaejeon btw are you interested in backport patches for 3.18 and 3.10? i have already finished this

**Comment by namjaejeon** [comment]
>  i have not seen this issue again. so its likelly fixed.

Thanks for your verification.

> btw are you interested in backport patches for 3.18 and 3.10? i have already finished this
Hm... These are too old kernels,  Is there still any demand for 3.18 and 3.10 kernel ? And These versions are not even LTS kernels...

**Comment by BrainSlayer** [comment]
@namjaejeon i dont know if there is for you. but i maintain a firmware for routers and on some of these i'm limited to a specific kernel version since the kernel size increased over time with newer versions which brings me into resource troubles. some routers only have 4 mb of flash storage and this turns everything complicated with newer kernels. for 3.10 i also have the issue with some broadcom devices that the pci bus is not working anymore on newer kernels. i dont know the reason yet, but i can just switch to newer kernels for these specific devices until i discovered the reason
i main my backport efforts are just a offer. i know that there might be no high demand for upstream efforts on your side

**Comment by namjaejeon** [comment]
@BrainSlayer  Previously, some users wanted to port ksmbd to 3.x kernel. Please share your patch and I will actively review it.

**Comment by BrainSlayer** [comment]
let me clean it up tomorrow. its a little bit messie right now and contains additional debug code you may not want and its only tested on 3.18 and 3.10 without any care about other versions in between
but all code i made can be reviewed on my svn server 
https://svn.dd-wrt.com/browser/src/router/smbd (svn://svn.dd-wrt.com/src/router/smbd)

**Comment by BrainSlayer** [comment]
i also stripped down all binaries and made a multicall binary out of it. so with a static linked glib and lto compiling usmbd etc is alltogether just 400kb which is very interesting for embedded applications. personally i want to get rid of glib completelly. it just increases size for no reason. everything in usmbd can be done without glib, just with pure posix code. then we can get the size bellow 100kb

**Comment by namjaejeon** [comment]
> let me clean it up tomorrow. 

Okay.

> personally i want to get rid of glib completelly. it just increases size for no reason. everything in usmbd can be done without glib, just with pure posix code. then we can get the size bellow 100kb

@BrainSlayer In the past, openWRT people also wanted to drop it. Sergey's thought was different from that. @sergey-senozhatsky Any opinion ?

**Comment by BrainSlayer** [comment]
@namjaejeon i already started with taking it out completelly and i will likelly be finished today but need to test the new code first. 90% is already done. glib is just bloatware. there its only used to rw locks  which can be replaced with phread_rwlock, its used for base64 encoding and decoding which can be easy replaced by a small own implementation. utf conversation can be replaced with iconv and finally there are some hashes and list implementations used. so no big deal

**Comment by namjaejeon** [comment]
@BrainSlayer Okay, I do not object. I want to check it after your work is done.

**Comment by BrainSlayer** [comment]
@namjaejeon due the massive  rewrite i did i expect alot of bugs. but i'm finished now and start to test and will fix them. usmbd / smbshareadd / smbuseradd is now 58kb in total as combined multicall binary on a mips platform

**Comment by namjaejeon** [comment]
@BrainSlayer Great work! We will also actively review it if you contribute the patch:)

**Comment by BrainSlayer** [comment]
@namjaejeon almost done now. i will commit it to my svn repository this evening. tests are successfull now after many hours of fixing issues. but before commiting do a deep carefull review. the patch isnt that small
ftp://ftp.dd-wrt.com/others/ksmbd/no-glib.patch

**Comment by BrainSlayer** [comment]
since its a incremental patch ,there might be small conflicts. so maybe also take a look into my repository since i modifie the makefile.am files earlier for multicall binary support

**Comment by namjaejeon** [comment]
@BrainSlayer Okay, BTW... I can't not apply your patch to ksmbd-tools... (git am or patch -p1). To review it on our mailing list, Does it need to convert ?

**Comment by BrainSlayer** [comment]
nope. but my local sourcetree has some small mods for debugging mainly. so some thing need to be merged manually. let me do a clean git checkout and do the job for you. gimme 15 minutes for it

**Comment by BrainSlayer** [comment]
mmh 
linux:/xfs/smbd/ksmbd-tools-3.1.0.new # patch -p1 < no-glib.patch
patching file lib/usmbdtools.c
patching file lib/config_parser.c
patching file lib/management/session.c
patching file lib/management/share.c
patching file lib/management/tree_conn.c
patching file lib/management/user.c
patching file include/usmbdtools.h
patching file include/config_parser.h
patching file include/management/session.h
patching file include/management/share.h
patching file include/management/tree_conn.h
patching file include/management/user.h
patching file include/rpc.h
patching file configure.ac
patching file smbshareadd/share_admin.c
patching file smbshareadd/smbshareadd.c
Hunk #2 succeeded at 107 (offset -4 lines).
patching file smbuseradd/smbuseradd.c
Hunk #2 succeeded at 106 (offset -4 lines).
patching file smbuseradd/user_admin.c
patching file usmbd/ipc.c
patching file usmbd/rpc.c
patching file usmbd/rpc_srvsvc.c
patching file usmbd/rpc_wkssvc.c
patching file usmbd/usmbd.c
Hunk #5 succeeded at 492 (offset -4 lines).
patching file usmbd/worker.c


applies without any issue to latest release version

**Comment by BrainSlayer** [comment]
i updated now the patch link to apply as clean patch again 3.1.0

**Comment by BrainSlayer** [comment]
so redownload any try again. i also compile tested it

**Comment by namjaejeon** [comment]
Okay, I checked it apply fine.
Thanks!
