### ISSUE TITLE
empty macro will lead to misscompiled code

### ISSUE THREAD

**Issue by BrainSlayer** [cifsd-team/ksmbd#296]
https://github.com/cifsd-team/smbd/blob/71e4e5004c82fb1f0e8000457d01625a4a75d730/glob.h#L45

example:

if (rc)
     smbd_debug("test);
free(somepointer);

what will happen if smbd_debug is a empty macro?
free will be never called unless rc is non zero. there are various locations in smbd where this condition will trigger. so smbd will not compiled correct if CONFIG_SMB_SERVER_DEBUGGING is disabled

-#define smbd_debug(fmt, ...)
+#define smbd_debug(fmt, ...) do { } while(0)

is the solution

**Comment by namjaejeon** [comment]
Right. Pushed your solution to next branch.(https://github.com/cifsd-team/smbd/pull/297/commits/b1d3849162bfe2cc7022e52f190b2efced2017de)

Thanks!

**Comment by sergey-senozhatsky** [comment]
On (20/01/18 19:57), Sebastian Gottschall wrote:
>    [1]https://github.com/cifsd-team/smbd/blob/71e4e5004c82fb1f0e8000457d01625a4a75d730/glob.h#L45
> 
>    example:
> 
>    if (rc)
>    smbd_debug("test);
>    free(somepointer);
> 
>    what will happen if smbd_debug is a empty macro?
>    free will be never called unless rc is non zero.

No. The pre-processed code will look like this

	if (rc)
		;
	free(somepointer);

	-ss

**Comment by BrainSlayer** [comment]
@sergey-senozhatsky its not that i have not tested this. the outcoming code does not work correct if debug is disabled at compile time.  authentication was not working etc. i was wondering why all was working correct if debugging is enabled, but not working if debugging is disabled. after that small patch all was going to work correct. (gcc 9 if that matters)

**Comment by sergey-senozhatsky** [comment]
@BrainSlayer I'm not objecting the patch. It's just the code sample given in the commit message won't be affected. AFAIU, we can have priblems when gcc sees zero-sized compound statements. E.g.

if (rc)
   smbd_debug("test);
else
   foo_bar();

But I need to check it.

-ss

**Comment by sergey-senozhatsky** [comment]
> It's just the code sample given in the commit message won't be affected. 

I take it back.
I played with various compilers and I see that some of them indeed swallow the semicolon.
Even in the simple case like the one in the commit message.

-ss

**Comment by BrainSlayer** [comment]
@sergey-senozhatsky yeah right was a bad sample. it was late at night

**Comment by namjaejeon** [comment]
Pushed the patch to master branch.
@BrainSlayer  Thanks for your report and solution!
