### ISSUE TITLE
ksmbd does not work if ipv6 module is not loaded or compiled in (patch inside)

### ISSUE THREAD

**Issue by BrainSlayer** [cifsd-team/ksmbd#308]
this patch allows to run ksmbd without ipv6 module beeing loaded. feel free to refine it.

ftp://ftp.dd-wrt.com/others/ksmbd/ksmbd_ipv4.patch

**Comment by namjaejeon** [comment]
Looks good to me. Let me your know your mail address. I would like to add your sign-off in this patch.
Thanks!

**Comment by BrainSlayer** [comment]
@namjaejeon  s.gottschall@dd-wrt.com

**Comment by namjaejeon** [comment]
Pushed it to next branch.
Thanks!

**Comment by namjaejeon** [comment]
Move it from next branch to master.
