### ISSUE TITLE
[Enhancement] Allow share flags/options to be applied globally

### ISSUE THREAD

**Issue by JpegXguy** [cifsd-team/ksmbd#516]
For example, with Samba I can specify `write list = someone` in the `[global]` section, and it will apply to all shares. I have 4-5 options that are basically applied to all my shares, yet I had to duplicate them all under every share section, in order for them to work.

**Comment by namjaejeon** [comment]
@JpegXguy I would appreciate if you directly work it.

**Comment by namjaejeon** [comment]
@JpegXguy @papadakospan improved it, Please try the latest ksmbd-tools.

**Comment by JpegXguy** [comment]
Works fine!
