### ISSUE TITLE
ksmbd requires FS_POSIX_ACL

### ISSUE THREAD

**Issue by neheb** [cifsd-team/ksmbd#526]
Is it possible to make this optional? OpenWrt does not use ACLs by default.

**Comment by namjaejeon** [comment]
Hi Rosen,

Could you please check the below patch ?
https://github.com/namjaejeon/ksmbd/commit/f408c6c45013c80d62ed4b793ee79d76e4b582e0

Thanks!

**Comment by neheb** [comment]
Works great.

**Comment by namjaejeon** [comment]
Thanks for test. I send the patch to list. It will be merged into master and release.

**Comment by namjaejeon** [comment]
@neheb ksmbd work fine with this patch as well as build success ?

**Comment by neheb** [comment]
Yes. This can be closed.
