### ISSUE TITLE
Error -22 mapping Owner SID to uid

### ISSUE THREAD

**Issue by pesa1234** [cifsd-team/ksmbd#545]
Dear guys...
I'm on ksmbd on my openwrt router... I have a strange issue...

Why when I try to make a new empty excel file with windows10 and office365 on my network folder I get these errors?

`Tue Nov 30 10:24:31 2021 kern.err kernel: [  939.193231] ksmbd: parse_sec_desc:814: parse_sec_desc: Error -22 mapping Owner SID to uid
Tue Nov 30 10:24:31 2021 kern.err kernel: [  939.201765] ksmbd: parse_sec_desc:829: parse_sec_desc: Error -22 mapping Group SID to gid
Tue Nov 30 10:24:31 2021 kern.err kernel: [  939.210269] ksmbd: parse_dacl:479: parse_dacl: Error -22 mapping Owner SID to uid
Tue Nov 30 10:24:31 2021 kern.err kernel: [  939.218073] ksmbd: parse_dacl:479: parse_dacl: Error -22 mapping Owner SID to uid`

Thanks in advance

**Comment by mmakassikis** [comment]
Which ksmbd/ksmbd-tools versions are you using ?
There are a few fixes regarding Windows/Office compatibility in the current code.

What filesystem is used on the disk backing the share ?

**Comment by pesa1234** [comment]
Hi, regarding filesystem I have same issue on fat32 and f2fs.
`ksmbd-server 3.4.2-1 | ksmbd-utils 3.4.2-1 | kmod-fs-ksmbd 5.4.154+3.3.9-1`

**Comment by namjaejeon** [comment]
Okay, Error message can be coming. So are there any problems with the operation excepting error print log ?

**Comment by pesa1234** [comment]
No ksmbd shows only that error, but my Win10 clients have an explorer restart on their computer and if they enter again on that folder they found two files:
```
~uovo Foglio di lavoro di Microsoft Excel.tmp
Nuovo Foglio di lavoro di Microsoft Excel.xlsx
```

**Comment by namjaejeon** [comment]
Okay, Can you show me parameters in the your smb.conf(/etc/ksmbd/smb.conf) ?

**Comment by namjaejeon** [comment]
I think that this patch(https://github.com/cifsd-team/ksmbd/commit/3b8d91be68c63a318c98458f870f439d5469d20d) will fix your issue. Once you can apply this patch to your target to fix issue right now. I will release 3.4.3 version after applying the flying patches on list.

**Comment by namjaejeon** [comment]
Can you confirm if problem is fixed or not ?

**Comment by pesa1234** [comment]
> Can you confirm if problem is fixed or not ?

I was not able to compile the package for my router yesterday...

**Comment by pesa1234** [comment]
Now I compiled it with https://github.com/cifsd-team/ksmbd/commit/3b8d91be68c63a318c98458f870f439d5469d20d, but the issue remain...

**Comment by namjaejeon** [comment]
Can send me a tcpdump on problem situation ?

**Comment by namjaejeon** [comment]
Ah I am missing one more patch. please apply this patch also https://github.com/namjaejeon/ksmbd/commit/4b1a35440024ee33c4a277350faf71f71fba7a1a

**Comment by pesa1234** [comment]
Hi, I've worked on file... this is the final patch applied, now on new excel file, windows explorer doesn't hangs, the file creation process is ok...

but, log on router
```
Mon Dec  6 00:16:24 2021 kern.err kernel: [20401.536432] ksmbd: Unsupported addition info: 0x1bf)
Mon Dec  6 00:16:25 2021 kern.err kernel: [20401.801239] ksmbd: Unsupported addition info: 0x1bf)
Mon Dec  6 00:16:32 2021 kern.err kernel: [20409.236681] ksmbd: Unsupported addition info: 0x3d)
Mon Dec  6 00:16:32 2021 kern.err kernel: [20409.242551] ksmbd: Unsupported addition info: 0x20)

```
```

--- a/smb2pdu.c
+++ b/smb2pdu.c
@@ -3770,6 +3770,24 @@ static int verify_info_level(int info_le
 	return 0;
 }
 
+static int smb2_calc_max_out_buf_len(struct ksmbd_work *work,
+				     unsigned short hdr2_len,
+				     unsigned int out_buf_len)
+{
+	int free_len;
+
+	if (out_buf_len > work->conn->vals->max_trans_size)
+		return -EINVAL;
+
+	free_len = (int)(work->response_sz -
+			 (get_rfc1002_len(work->response_buf) + 4)) -
+		hdr2_len;
+	if (free_len < 0)
+		return -EINVAL;
+
+	return min_t(int, out_buf_len, free_len);
+}
+
 int smb2_query_dir(struct ksmbd_work *work)
 {
 	struct ksmbd_conn *conn = work->conn;
@@ -4418,6 +4436,9 @@ static void get_file_stream_info(struct
 	struct path *path = &fp->filp->f_path;
 	ssize_t xattr_list_len;
 	int nbytes = 0, streamlen, stream_name_len, next, idx = 0;
+	int buf_free_len;
+	struct smb2_query_info_req *req = ksmbd_req_buf_next(work);
+
 
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 12, 0)
 	generic_fillattr(file_mnt_user_ns(fp->filp), file_inode(fp->filp), &stat);
@@ -4426,6 +4447,12 @@ static void get_file_stream_info(struct
 #endif
 	file_info = (struct smb2_file_stream_info *)rsp->Buffer;
 
+	buf_free_len =
+		smb2_calc_max_out_buf_len(work, 8,
+					  le32_to_cpu(req->OutputBufferLength));
+	if (buf_free_len < 0)
+		goto out;
+
 	xattr_list_len = ksmbd_vfs_listxattr(path->dentry, &xattr_list);
 	if (xattr_list_len < 0) {
 		goto out;
@@ -4473,7 +4500,10 @@ static void get_file_stream_info(struct
 		file_info->NextEntryOffset = cpu_to_le32(next);
 	}
 
-	if (!S_ISDIR(stat.mode)) {
+out:
+
+	if (!S_ISDIR(stat.mode)){
+
 		file_info = (struct smb2_file_stream_info *)
 			&rsp->Buffer[nbytes];
 		streamlen = smbConvertToUTF16((__le16 *)file_info->StreamName,
@@ -4487,7 +4517,7 @@ static void get_file_stream_info(struct
 
 	/* last entry offset should be 0 */
 	file_info->NextEntryOffset = 0;
-out:
+
 	kvfree(xattr_list);
 
 	rsp->OutputBufferLength = cpu_to_le32(nbytes);

```

**Comment by namjaejeon** [comment]
Great! And ignore error message. it is not related with your issue. please see this patch(https://github.com/namjaejeon/ksmbd/commit/7a97df68f3e3df06a5f9e2e97f99e6cdbdf7f3ae)

**Comment by pesa1234** [comment]
Ok, I hope that these already fixed things goes to the stable release soon...

So, issue can be closed

**Comment by namjaejeon** [comment]
Thanks for your work! closed.
