### ISSUE TITLE
Large file transfer to smb share exfat partition from windiws client

### ISSUE THREAD

**Issue by PoleTIC** [cifsd-team/ksmbd#547]
Hi,

Some clients are experiencing some issues. Using ksmbd-3.3.4, transferring large files (2go) to smb shared exfat usb disk fails from  windows client (windows 10) with windows error 0x8007003B (Unattended network error). Note that, the problem is not seen from linux client neither using NTFS filesystem.  Have you any idea on what can be the cause of such an issue ?

Regards

**Comment by mmakassikis** [comment]
Hi,

Please test with newer version of ksmbd/ksmbd-tools. There have been many changes since 3.3.4.

**Comment by PoleTIC** [comment]
HI mmakassikis,
Thanks. I will test with newer version and get back my feedback.

**Comment by namjaejeon** [comment]
@PoleTIC Please check https://github.com/cifsd-team/ksmbd-tools/issues/219.
I didn't apply this patch to ksmbd yet. Will do that. You can apply the change in above ISSUE if you want to fix ASAP.

**Comment by PoleTIC** [comment]
Thx @namjaejeon. The fix works well.
