### ISSUE TITLE
A kernel Null reference and crash cuased by SMB command

### ISSUE THREAD

**Issue by PoleTIC** [cifsd-team/ksmbd#548]
A Null pointer reference in kernel has been observed when using the smbclient "volume" command causing a kernel crash. Tested on ksmbd (3.3.7) as follows:
$ smbclient //192.168.2.1/ipc$
$ smb: \> volume

There is any fix intended to this issue ?

Regards

**Comment by namjaejeon** [comment]
At least, you need to share kernel oops backtrace.

linkinjeon@linkinjeon-Z10PA-D8-Series:~$ smbclient //172.30.1.20/ipc$
Enter WORKGROUP\linkinjeon's password: 
Try "help" to get a list of possible commands.
smb: \> volume
Error NT_STATUS_INVALID_PARAMETER getting volume info
smb: \>

**Comment by PoleTIC** [comment]
I will test on the latest version and put the backtrace if the issue is still there. Thanks

**Comment by PoleTIC** [comment]
Issue not reproduced on version 3.4.2. Closing the ticket.
