### ISSUE TITLE
Cannot compile on Debian11

### ISSUE THREAD

**Issue by s0urcelab** [cifsd-team/ksmbd#566]
OS: Debian11 with kernel 5.10.0-15-amd64

as [https://unix.stackexchange.com/questions/657157/building-ksmbd-on-debian-buster-bpo](https://unix.stackexchange.com/questions/657157/building-ksmbd-on-debian-buster-bpo) said:

- install linux-source-5.10 by apt
- try to edit fs/Kconfig and fs/Makefile as README said, but found none of them.
- make allmodconfig
- make fs/ksmbd/ksmbd.ko

but throw some error:

root@HTPC:/tmp/tmp.nmMkxqcoli/linux-source-5.10# make fs/ksmbd/ksmbd.ko
  SYNC    include/config/auto.conf.cmd
  CC      arch/x86/kernel/asm-offsets.s
In file included from ./include/linux/memcontrol.h:13,
                 from ./include/linux/swap.h:9,
                 from ./include/linux/suspend.h:5,
                 from arch/x86/kernel/asm-offsets.c:13:
./include/linux/cgroup.h: In function ‘cgroup_ino’:
./include/linux/cgroup.h:627:9: error: implicit declaration of function ‘kernfs_ino’; did you mean ‘kernfs_init’? [-Werror=implicit-function-declaration]
  627 |  return kernfs_ino(cgrp->kn);
      |         ^~~~~~~~~~
      |         kernfs_init
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:117：arch/x86/kernel/asm-offsets.s] 错误 1
make: *** [Makefile:1204：prepare0] 错误 2

**Comment by namjaejeon** [comment]
> ./include/linux/cgroup.h:627:9: error: implicit declaration of function ‘kernfs_ino’; did you mean ‘kernfs_init’? [-Werror=implicit-function-declaration]

build error is not related with ksmbd ? I don't think that it is ksmbd issue. Please see where build error is coming.

**Comment by consp** [comment]
Why try to build with kernel sources? What is the point? Have you tried building ksmbd form github outside of the kernel source?

* Install kernel headers and common headers and required build tools
* Clone github to somewhere
* cd somewhere
* `make`
* `make install`

**Comment by shige-fami** [comment]
This might help you; https://kamikopanda.ddns.net/2022/08/09/ksmbdsmbdirect-works/
